env:
    CIRRUS_CLONE_DEPTH: 1
    CIRRUS_WORKING_DIR: "/tmp/ci"
    CIRRUS_SHELL: bash

task:
    name: tools
    timeout_in: 2h
    container:
      image: aarunalr/aosp-build
      cpu: 8
      memory: 32g
    
    setup_script:
      - git clone https://github.com/ShivamKumarJha/android_tools 
      - bash android_tools/setup.sh

    dump_script:
      - bash run.sh
