env:
    CIRRUS_CLONE_DEPTH: 1
    CIRRUS_WORKING_DIR: "/tmp/ci"
    CIRRUS_SHELL: bash
    token: ENCRYPTED[cbd94818902777c189d0dde3d355d471f837917f612bb1650d258172a2226f6e7e7e4799cdd6bd8a8775f63dbefec8a1]
    chat_id: ENCRYPTED[220350a1eefa98aaa8b47115d9c9937410e32e67f93bdb93e08af68b6ca9c8acd4f9446c4b0aada3990f0f5cf1f38fa3]
    tg_token: ENCRYPTED[4760ab98ee914a604578bef77cbd61b98f6f2464fa0fae7c412b720bc284e8e7438ebbe57dba9730478b39dcc924995b]

task:
    name: dump
    timeout_in: 2h
    container:
      image: aarunalr/aosp-build
      cpu: 8
      memory: 32g
    
    setup_script:
      - curl -Ls https://raw.githubusercontent.com/ShivamKumarJha/android_tools/master/setup.sh | bash
    dump_script:
      - wget https://raw.githubusercontent.com/DroidDumps/phoenix_firmware_dumper/main/dumper.sh
      - bash dump.sh
