env:
    CIRRUS_CLONE_DEPTH: 1
    CIRRUS_WORKING_DIR: "/tmp/ci"
    CIRRUS_SHELL: bash
    github_token: "ENCRYPTED[!8d7c0b443761c7202dfcd0eab5a6f77cefde52d640ee37958c26a7b7907f0423769c395f55f32b5e06abda073649f4e8!]"
    bot_api: "ENCRYPTED[!1b963e398f443d96991c906f64c6e1769c246ff2c873874b99985d62a8ebec7a4aae5d3aab615b454858b62310dfd132!]"
    chat_id: "ENCRYPTED[!7e9c1abd52a2d0165baa9ee729c09ff72904cdc7fb48ffe9395ab5f2e5d142eee5b0119d1b2df74e4725b1e109e16541!]"

task:
    name: dump
    timeout_in: 2h
    container:
      image: aarunalr/aosp-build
      cpu: 8
      memory: 32g

    setup_script:
      - git clone https://github.com/XenStuff/phoenix_firmware_dumper 
      - bash phoenix_firmware_dumper/setup.sh

    dump_script:
      - bash dump.sh
